
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int fi_si = 31;
  public static final int cadena = 23;
  public static final int not = 20;
  public static final int numero = 4;
  public static final int mayorOIgual = 15;
  public static final int mientras = 25;
  public static final int por = 7;
  public static final int fmientras = 27;
  public static final int hacer = 26;
  public static final int or = 18;
  public static final int caracter = 22;
  public static final int menos = 6;
  public static final int igualLogico = 17;
  public static final int inicio = 2;
  public static final int EOF = 0;
  public static final int division = 8;
  public static final int menorOIgual = 16;
  public static final int potencia = 9;
  public static final int error = 1;
  public static final int parC = 12;
  public static final int comentario = 24;
  public static final int parA = 11;
  public static final int fin = 3;
  public static final int diferente = 21;
  public static final int mas = 5;
  public static final int menorQue = 14;
  public static final int si = 28;
  public static final int mod = 10;
  public static final int and = 19;
  public static final int de_lo_contrario = 30;
  public static final int o_si = 29;
  public static final int mayorQue = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio",
  "fin",
  "numero",
  "mas",
  "menos",
  "por",
  "division",
  "potencia",
  "mod",
  "parA",
  "parC",
  "mayorQue",
  "menorQue",
  "mayorOIgual",
  "menorOIgual",
  "igualLogico",
  "or",
  "and",
  "not",
  "diferente",
  "caracter",
  "cadena",
  "comentario",
  "mientras",
  "hacer",
  "fmientras",
  "si",
  "o_si",
  "de_lo_contrario",
  "fi_si"
  };
}

