
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int potencia = 9;
  public static final int parC = 12;
  public static final int parA = 11;
  public static final int inicio = 2;
  public static final int EOF = 0;
  public static final int menos = 6;
  public static final int division = 8;
  public static final int numero = 4;
  public static final int error = 1;
  public static final int mod = 10;
  public static final int por = 7;
  public static final int fin = 3;
  public static final int mas = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio",
  "fin",
  "numero",
  "mas",
  "menos",
  "por",
  "division",
  "potencia",
  "mod",
  "parA",
  "parC"
  };
}

